version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Australia/Melbourne"
    groups:
      github:
        patterns:
          - "*"
    labels:
      - "ci"
      - "dependencies"
